### ISSUE TITLE
Packet ID Error

### ISSUE THREAD

**Issue by valicu001** [kaos00723/RotMG_Client_27.7.X2#4]
When I try to click play,It doesn't load me into nexus and gives me this error:
Packer ID not found: 35
Socket error.
System.NullReferenceException: Object reference not set to an instance of an object.

**Comment by kaos00723** [comment]
I don't know what you are trying to do but this client works 100% when used correctly. If you are trying to convert it for use with a private server then please ask questions on the forum that led you here, I won't help with that. If you are trying to connect to the live servers then several things would need to be changed due to updates.

**Comment by valicu001** [comment]
I was wondering that I might have done the convertion wrong.Do I need to put the updated version into the FSOD folder or the other way around?

**Comment by valicu001** [comment]
Nvm,sorry.Now I know what u are talking about.Thank you for the reply.
