### ISSUE TITLE
Updated Client

### ISSUE THREAD

**Issue by slick1015** [kaos00723/RotMG_Client_27.7.X2#5]
I made an updated version of this over at https://github.com/slick1015/rotmg-client and I would love it if you could come and help fix some bugs that are noted over on this thread: http://www.mpgh.net/forum/showthread.php?t=1192910

**Comment by kaos00723** [comment]
There really isn't much of a reason to try and completely convert it to X8 from X2 at this time. Replacing the XML's and images with updated ones and a couple other minor edits would be the best way to update it. There was nothing added since X2 that would benefit a private server feature wise from what I can tell.

**Comment by slick1015** [comment]
@kaos00723 I am not doing this for pservers, I am doing this for more than that. I am doing it so there is a working prod client that people can test out their own hacks and make their own. I am sure people will also be able to learn a lot about how the client works too.

**Comment by kaos00723** [comment]
You can still connect to live with this if you fix any packet structure changes and what not. I know the Hello packet and Object data structures changed since X2, maybe more. You shouldn't need to do much more than that to get this working with live besides updating XML's and images as well. If you are trying to get this identical to X8 code wise then you would be better off creating a new client from scratch instead of trying to fix errors.

**Comment by kaos00723** [comment]
I created a new branch that works with 27.7.X8 here: https://github.com/kaos00723/RotMG_Client_27.7.X2/tree/27.7.X8
